# Make rules for configuration files.
#
# $Id$

CFG		= kernel

CONFIGFILES	= \
	$(CFG)-adaptation-intel-automotive.config \

PLATFORMS	= x86 arm
TEMPFILES	= $(addprefix temp-, $(addsuffix -generic, $(PLATFORMS)))

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)
	@rm -f temp-generic temp-*-generic temp-*-generic-tmp

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config

kernel-adaptation-intel-automotive.config: config-adaptation-intel-automotive config-generic
	perl merge.pl $^  > $@
